language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - android-25
    - build-tools-25.0.2
    - platform-tools
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew clean check

branches:
  only:
  - master
  - dev

after_success:
  - ./gradlew jacocoTestReport coveralls