language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew clean assembleDebug testDebug